apiVersion: apps/v1
kind: Deployment
metadata:
  name: index
  labels:
    app: index
spec:
  replicas: 2
  selector:
    matchLabels:
      app: index
  template:
    metadata:
      labels:
        app: index
    spec:
      containers:
      - name: index
        image: 340752836801.dkr.ecr.ap-south-1.amazonaws.com/index:latest
        ports:
        - containerPort: 80
